-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PERSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSON` (
  `PERSON_ID` INT NOT NULL AUTO_INCREMENT,
  `PERSON_FIRSTNAME` VARCHAR(45) NULL,
  `PERSON_LASTNAME` VARCHAR(45) NULL,
  `PERSON_EMAIL` VARCHAR(45) NULL,
  `PERSON_PASSWORD` CHAR(60) NULL,
  `PERSON_PHONE` VARCHAR(45) NULL,
  PRIMARY KEY (`PERSON_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESTAURANT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESTAURANT` (
  `RESTAURANT_ID` INT NOT NULL AUTO_INCREMENT,
  `RESTAURANT_NAME` VARCHAR(45) NULL,
  `RESTAURANT_OWNER` INT NULL,
  `RESTAURANT_POSTCODE` VARCHAR(45) NULL,
  `RESTAURANT_STREET` VARCHAR(45) NULL,
  `RESTAURANT_CITY` VARCHAR(45) NULL,
  `RESTAURANT_TABLE_COUNT` INT NULL,
  `RESTAURANT_PRE_BOOK` TINYINT NULL,
  PRIMARY KEY (`RESTAURANT_ID`),
  INDEX `R_OWN_PERSON_idx` (`RESTAURANT_OWNER` ASC),
  CONSTRAINT `R_OWN_PERSON`
    FOREIGN KEY (`RESTAURANT_OWNER`)
    REFERENCES `mydb`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STATUS` (
  `STATUS_ID` INT NOT NULL AUTO_INCREMENT,
  `STATUS_DESCRIPTION` VARCHAR(45) NULL,
  PRIMARY KEY (`STATUS_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDER_HEADER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ORDER_HEADER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `RESTAURANT_ID` INT NULL,
  `ORDER_HEADER` VARCHAR(45) NULL,
  `ORDER_ORDERED_BY` INT NULL,
  `ORDER_STATUS` INT NULL,
  PRIMARY KEY (`ORDER_ID`),
  INDEX `ORD_RESTAURANT_idx` (`RESTAURANT_ID` ASC),
  INDEX `ORD_PERSON_idx` (`ORDER_ORDERED_BY` ASC),
  INDEX `ORDER_STATUS_idx` (`ORDER_STATUS` ASC),
  CONSTRAINT `ORD_RESTAURANT`
    FOREIGN KEY (`RESTAURANT_ID`)
    REFERENCES `mydb`.`RESTAURANT` (`RESTAURANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORD_PERSON`
    FOREIGN KEY (`ORDER_ORDERED_BY`)
    REFERENCES `mydb`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORDER_STATUS`
    FOREIGN KEY (`ORDER_STATUS`)
    REFERENCES `mydb`.`STATUS` (`STATUS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MENUTYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MENUTYPE` (
  `MENU_TYPE_ID` INT NOT NULL AUTO_INCREMENT,
  `MENU_CATEGORY` VARCHAR(45) NULL,
  PRIMARY KEY (`MENU_TYPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REVIEW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REVIEW` (
  `REVIEW_ID` INT NOT NULL AUTO_INCREMENT,
  `RESTAURANT_ID` INT NULL,
  `REVIEW_COMMENTS` VARCHAR(45) NULL,
  `REVIEW_RATING` VARCHAR(45) NULL,
  `REVIEW_PERSON` INT NULL,
  PRIMARY KEY (`REVIEW_ID`),
  INDEX `REVIEW_RESTAURANT_idx` (`RESTAURANT_ID` ASC),
  INDEX `REVIEW_PERSON_idx` (`REVIEW_PERSON` ASC),
  CONSTRAINT `REVIEW_RESTAURANT`
    FOREIGN KEY (`RESTAURANT_ID`)
    REFERENCES `mydb`.`RESTAURANT` (`RESTAURANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `REVIEW_PERSON`
    FOREIGN KEY (`REVIEW_PERSON`)
    REFERENCES `mydb`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT` (
  `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_PRICE` DECIMAL(15,2) NULL,
  `PRODUCT_NAME` VARCHAR(45) NULL,
  `PRODUCT_MENU_TYPE` INT NULL,
  `RESTAURANT_ID` INT NULL,
  `PRODUCT_REVIEW_ID` INT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  INDEX `PROD_REST_idx` (`RESTAURANT_ID` ASC),
  INDEX `MENU_TYPE_idx` (`PRODUCT_MENU_TYPE` ASC),
  INDEX `PROD_REVIEW_idx` (`PRODUCT_REVIEW_ID` ASC),
  CONSTRAINT `PROD_REST`
    FOREIGN KEY (`RESTAURANT_ID`)
    REFERENCES `mydb`.`RESTAURANT` (`RESTAURANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MENU_TYPE`
    FOREIGN KEY (`PRODUCT_MENU_TYPE`)
    REFERENCES `mydb`.`MENUTYPE` (`MENU_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROD_REVIEW`
    FOREIGN KEY (`PRODUCT_REVIEW_ID`)
    REFERENCES `mydb`.`REVIEW` (`REVIEW_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDER_ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ORDER_ITEM` (
  `ORDERITEM_ID` INT NOT NULL AUTO_INCREMENT,
  `ORDER_ID` INT NULL,
  `QUANTITY` INT NULL,
  `PRODUCT_ID` INT NULL,
  PRIMARY KEY (`ORDERITEM_ID`),
  INDEX `ORD_ID_ORD_ITM_idx` (`ORDER_ID` ASC),
  INDEX `ORD_ITM_PROD_idx` (`PRODUCT_ID` ASC),
  CONSTRAINT `ORD_ID_ORD_ITM`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `mydb`.`ORDER_HEADER` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORD_ITM_PROD`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `mydb`.`PRODUCT` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAYMENT_METHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAYMENT_METHOD` (
  `PAYMENT_METHOD_ID` INT NOT NULL AUTO_INCREMENT,
  `PAYMENT_METHOD_TYPE` VARCHAR(15) NULL,
  `PERSON_ID` INT NULL,
  `PAYMENT_CARD` CHAR(16) NULL,
  `PAYMENT_EXPIRY` DATE NULL,
  `PAYMENT_CVC` CHAR(3) NULL,
  PRIMARY KEY (`PAYMENT_METHOD_ID`),
  INDEX `PAY_PERSON_idx` (`PERSON_ID` ASC),
  CONSTRAINT `PAY_PERSON`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `mydb`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
set global sql_mode='';
